#!/bin/bash

if [[ "$OSTYPE" =~ ^darwin ]]; then
  DEFAULT_PATH="~/SimplicityStudio/SDKs/gsdk_4_4_1"
elif [ -f /.dockerenv ]; then
  DEFAULT_PATH="/gecko_sdk/"
else
  DEFAULT_PATH=
fi

GIT_VERSION="$(git describe --abbrev=4 --dirty --always --tags --all --match releases/*)"

GSDK_PATH=${GSDK_PATH:=$DEFAULT_PATH}

rm -rf ./out
slc generate -s ${GSDK_PATH} -p EFR32xG22_OEPL.slcp -o makefile -d ./out -cp
cd out

# For some reason, the autogenerated makefile insists on not allowing C define
# overrides. So patch it before running make.
if [[ "$OSTYPE" =~ ^darwin ]]; then
sed -i '' 's/C_DEFS   =/C_DEFS ?=/' EFR32xG22_OEPL.Makefile
else
sed -i 's/C_DEFS   =/C_DEFS ?=/' EFR32xG22_OEPL.Makefile
fi

# The SDK insists on using LFXO, even though some of the tags don't have
# it. Patch the autogenerated file to fall back on LFRCO.
if [[ "$OSTYPE" =~ ^darwin ]]; then
  sed -i '' 's/, LFXO/, LFRCO/' autogen/sl_device_init_clocks.c
  sed -i '' 's/ sl_device_init_lfxo/\/\/ sl_device_init_lfxo/' autogen/sl_event_handler.c
else
  sed -i 's/, LFXO/, LFRCO/' autogen/sl_device_init_clocks.c
  sed -i 's/ sl_device_init_lfxo/\/\/ sl_device_init_lfxo/' autogen/sl_event_handler.c
fi

# The debug USART defaults to blocking sleep to enable RX. Since we're not relying
# on RX, turn it off.
# Note: this is probably a bug in the project generator, as this is already attempting
# to be set in the .slcp, but somehow it doesn't take effect.
if [[ "$OSTYPE" =~ ^darwin ]]; then
  sed -i '' 's/SL_IOSTREAM_EUSART_EUART_DEBUG_RESTRICT_ENERGY_MODE_TO_ALLOW_RECEPTION    1/SL_IOSTREAM_EUSART_EUART_DEBUG_RESTRICT_ENERGY_MODE_TO_ALLOW_RECEPTION    0/' config/sl_iostream_eusart_euart_debug_config.h
else
  sed -i 's/SL_IOSTREAM_EUSART_EUART_DEBUG_RESTRICT_ENERGY_MODE_TO_ALLOW_RECEPTION    1/SL_IOSTREAM_EUSART_EUART_DEBUG_RESTRICT_ENERGY_MODE_TO_ALLOW_RECEPTION    0/' config/sl_iostream_eusart_euart_debug_config.h
fi

env C_DEFS=-DGIT_COMMIT_ID=\\\"${GIT_VERSION#tags/releases/}\\\" make -f EFR32xG22_OEPL.Makefile -j8
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Error building firmware"
    exit $retVal
else
    echo "Built firmware ${GIT_VERSION#tags/releases/}"
fi

cd ..
cp out/build/debug/EFR32xG22_OEPL.s37 firmware.s37
